export const specialities = [
  {
    id: "12",
    name: "Інженерія програмного забезпечення",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Факультет Інформатики",
  },
  {
    id: "2",
    name: "Інженерія програмного забезпечення",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Факультет Інформатики",
  },
  {
    id: "44",
    name: "Інженерія програмного забезпечення",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Факультет Інформатики",
  },
  {
    id: "4",
    name: "Інженерія програмного забезпечення",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Факультет Інформатики",
  },
  {
    id: "5",
    name: "Комп'ютерні науки",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Комп'ютерні науки",
  },
  {
    id: "3",
    name: "Комп'ютерні науки",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Комп'ютерні науки",
  },
  {
    id: "1",
    name: "Інженерія програмного забезпечення",
    number: 121,
    numberOfCurses: 4,
    price: 30_000,
    avaliablePlaces: 100,
    totalPlaces: 100,
    budgetPlaces: 50,
    contractPlaces: 50,
    educationForm: "Денна",
    faculty: "Факультет Інформатики",
  },
];
